### ISSUE TITLE
OutOfMemmory after done button

### ISSUE THREAD

**Issue by thealeksandr** [jdamcd/android-crop#88] opened 2015-03-02 09:47 UTC
Get this error after tried save image. maybe it because parameters withMaxSize don't work.
```
java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:650)
            at com.soundcloud.android.crop.CropImageActivity.setupFromIntent(CropImageActivity.java:134)
            at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
            at android.app.Activity.performCreate(Activity.java:5192)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
            at android.app.ActivityThread.access$600(ActivityThread.java:140)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4898)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jdamcd** [comment] 2015-04-17 17:01
Closing as a duplicate of #32. Next release should fix maxSize issues, but there is always a risk of OOM where large images are involved.

**Closed by jdamcd** 2015-04-17 17:01 UTC
