### ISSUE TITLE
No such file or directory exception

### ISSUE THREAD

**Issue by tigercbc** [jdamcd/android-crop#144] opened 2015-07-21 09:06 UTC
I got images by using the camera, and saved in SD card. The Uri string is like 'file:///storage/emulated/0/1437469321272.jpg'. 

please help!

**Comment by jdamcd** [comment] 2015-09-07 09:31
I'm afraid there isn't much I can do without a lot more detail. Please feel free to re-open the issue with a full stack trace. Are you able to access the image at that `Uri` otherwise? Is this a duplicate of https://github.com/jdamcd/android-crop/issues/79?

**Closed by jdamcd** 2015-09-07 09:31 UTC
