### ISSUE TITLE
ERROR: When crop multiple images

### ISSUE THREAD

**Issue by dotnata** [jdamcd/android-crop#82] opened 2015-02-14 00:43 UTC
I need crop 4 images, do the procedure through four buttons one by one, all ok, even when crop the 3 image application closes. this shows the logcat:

    VM aborting 
    Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 30361
    02-13 19:31:06.691: E/dalvikvm-heap(31002): Out of memory on a 9437200-byte allocation.
    02-13 19:31:06.721: D/skia(31002): --- decoder->decodeRegion returned false
    02-13 19:31:06.731: E/android-crop(31002): OOM cropping image: null
    02-13 19:31:06.731: E/android-crop(31002): java.lang.OutOfMemoryError
    02-13 19:31:06.731: E/android-crop(31002): at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
    02-13 19:31:06.731: E/android-crop(31002): 	at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:186)
    02-13 19:31:06.731: E/android-crop(31002): 	at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:356)
    02-13 19:31:06.731: E/android-crop(31002): 	at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:298)
    02-13 19:31:06.731: E/android-crop(31002): 	at com.soundcloud.android.crop.CropImageActivity.access$9(CropImageActivity.java:265)
    02-13 19:31:06.731: E/android-crop(31002): 	at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:109)
    02-13 19:31:06.731: E/android-crop(31002): 	at android.view.View.performClick(View.java:4101)
    02-13 19:31:06.731: E/android-crop(31002): 	at android.view.View$PerformClick.run(View.java:17082)
    02-13 19:31:06.731: E/android-crop(31002): 	at android.os.Handler.handleCallback(Handler.java:615)
    02-13 19:31:06.731: E/android-crop(31002): 	at android.os.Handler.dispatchMessage(Handler.java:92)
    02-13 19:31:06.731: E/android-crop(31002): 	at android.os.Looper.loop(Looper.java:137)
    02-13 19:31:06.731: E/android-crop(31002): 	at android.app.ActivityThread.main(ActivityThread.java:4929)
    02-13 19:31:06.731: E/android-crop(31002): 	at java.lang.reflect.Method.invokeNative(Native Method)
    02-13 19:31:06.731: E/android-crop(31002): 	at java.lang.reflect.Method.invoke(Method.java:511)
    02-13 19:31:06.731: E/android-crop(31002): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
    02-13 19:31:06.731: E/android-crop(31002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
    02-13 19:31:06.731: E/android-crop(31002): 	at dalvik.system.NativeStart.main(Native Method)

and updated the library, the dimensions of the images are 1536x2048 and 2048x1536 (images from the camera phone)

**Comment by danielwilson1702** [comment] 2015-02-14 16:58
This is nothing to do with the library, what device are you using? What's happening is too many high resolution images are being loaded into RAM . So you'll need to either decrease the resolution of the images, subsample them as per the Android documentation on loading large bitmaps efficiently, or take time to carefully make sure only one image is ever loaded into RAM.

**Comment by dotnata** [comment] 2015-02-15 16:18
I am using an LG L3 with 500 mb of ram.
I was thinking the same thing has nothing to do with the library. thanks for the tips.

**Comment by TiagoGouvea** [comment] 2015-02-22 21:15
I'm having the same here with a Galaxy SIII with 1GB RAM, but cropping just one image.
The picture I'm trying to crop are taken from phone camera and have 3264x2448.

**Comment by jdamcd** [comment] 2015-04-17 16:58
Closing as a duplicate of #33. In general, there is a limit to how much the library can do here. If you're already close to the limit and you try and crop a huge image it's not going to go well.

**Closed by jdamcd** 2015-04-17 16:58 UTC
